### ISSUE TITLE
[JOSS REVIEW] BSD 4-Clause License is not OSI approved

### ISSUE THREAD

**Issue by finsberg** [marchirschvogel/ambit#2]
According to https://opensource.org/licenses/?ls=BSD BSD 4-Clause is not OSI approved which is a [requirement for JOSS](https://joss.readthedocs.io/en/latest/review_criteria.html#software-license). 

This is related to https://github.com/openjournals/joss-reviews/issues/5744

**Comment by marchirschvogel** [comment]
Thanks for pointing to this. I now moved the code to the MIT license.
