### ISSUE TITLE
Add automated tests

### ISSUE THREAD

**Issue by finsberg** [marchirschvogel/ambit#4]
There are a lot of tests in the repository and there should be a process for running these tests whenever someone pushes to the `main` (or `master` in this case) branch.

Please add a GitHub action (or using another provider) for running these tests.

This is related to https://github.com/openjournals/joss-reviews/issues/5744

**Comment by marchirschvogel** [comment]
Thanks for pointing to this. I've added an automated install and testing workflow (.github/workflows/test.yml) that is executed at each push event to the master branch.
