### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by finsberg** [marchirschvogel/ambit#5]
I think the documentation that you have written in https://github.com/marchirschvogel/ambit/blob/master/doc/ambit_doc.pdf is really good, and I think it deserves to be added as a part on an online documentation hosted on e.g GitHub pages or [Read The Docs](https://about.readthedocs.com/?ref=readthedocs.com). This is fairly low effort and makes the user experience drastically better. For example you can convert the latex file to markdown using [pandoc](https://pandoc.org) and use some tool to turn this into an online documentation (you can read about some of the tools [here](https://realpython.com/documenting-python-code/#documentation-tools-and-resources))

As a part of this I also think you should also add API documentation and make sure to also add docstrings to the APIs that a user would need to use. 

This is related to https://github.com/openjournals/joss-reviews/issues/5744

**Comment by marchirschvogel** [comment]
Thanks for pointing to this, I was not aware of these tools for documentation. I've now put the whole documentation on https://ambit.readthedocs.io/ and indeed think that this will enhance user experience.

I am not quite sure yet how to best add API documentation and if docstrings need to be added to each function/class. The user actually only interacts with the main function by passing lists of dictionaries and would not need to call lower level functions.
But I will keep that on my agenda and am happy to receive any advice.

Let me know if the issue can be closed at that stage or whether further aspects need to be considered.

**Comment by finsberg** [comment]
Hi @marchirschvogel! Great job, I think this looks really good!
Regarding doc strings I think you should add docstrings to the functions that a user interacts with, i.e at least need to have this on the main function. To generate documentation directly from docstrings you can e.g use `sphinx-apidoc` see https://www.sphinx-doc.org/en/master/man/sphinx-apidoc.html and https://www.sphinx-doc.org/en/master/tutorial/automatic-doc-generation.html

Also would it be possible to add the demos as a part of the online documentation?

**Comment by marchirschvogel** [comment]
Thanks, I've made use of the sphinx-apidoc and added docstrings to the main function the user calls. Strangely, the docstrings are only shown in my local sphinx html build, but not on Readthedocs. I'll check what the issue could be.

Also, I've moved the demos description to the documentation.

**Comment by finsberg** [comment]
Looks great!
