### ISSUE TITLE
[JOSS REVIEW] State of the field

### ISSUE THREAD

**Issue by finsberg** [marchirschvogel/ambit#7]
The [joss paper](https://github.com/marchirschvogel/ambit/blob/master/joss/paper.md) is missing a section about the *State of the  field* where you compare your software to other commonly-used packages.

This is related to https://github.com/openjournals/joss-reviews/issues/5744

**Comment by marchirschvogel** [comment]
Thanks, I've updated the paper.md file accordingly, and included a paragraph under the "Statement of need" section on other open source solvers tailored towards cardiac mechanics. Please let me know if you feel that I've forgotten to mention any other important package(s).
